### ISSUE TITLE
Joomla User Group Changes After Each Login

### ISSUE THREAD

**Issue by jgentles** [lcdservices/CiviCRM-CiviAuthenticate#7] opened 2015-04-30 00:14 UTC
Hi,

When I enable the plugin it sets the users Joomla user group every other login. So the first time the person logs in they are assigned to the correct Joomla group. When they log out and log back in they are removed from the Joomla user group. When they log back in again they are assigned the correct user group. It's really weird because every time the person logs in the permission is either set or totally removed.

I am running CiviCRM 4.6.2 and Joomla 2.5.28. I have the Joomla and CiviAuthenticate plugins enabled with the CiviAuthenticate first. I've attached the screen settings that I am using with CiviAuthenticate.

![civiauthenticate-membership-type-access-control](https://cloud.githubusercontent.com/assets/1371962/7404038/77ce5516-eeab-11e4-946b-d3d247efa7e7.png)

![cviauthenticate-login-behavior](https://cloud.githubusercontent.com/assets/1371962/7404040/77d01aae-eeab-11e4-926f-97348c1c9147.png)

![cviauthenticate-status-access-control](https://cloud.githubusercontent.com/assets/1371962/7404039/77cf899a-eeab-11e4-9099-6450dd2de22c.png)

**Comment by jgentles** [comment] 2015-07-20 16:29
Is this project abandoned?

**Comment by lcdservices** [comment] 2015-07-20 16:30
no. but I've been unable to reproduce this issue (and have had limited time to work on it)

**Comment by jgentles** [comment] 2015-07-20 16:40
Thank you for the reply...In your testing do you have the Authentication - Joomla enabled?

**Comment by lcdservices** [comment] 2018-02-09 20:58
the plugin has undergone a number of updates since this ticket was opened. closing as no longer able to replicate.

**Closed by lcdservices** 2018-02-09 20:58 UTC
